### PR TITLE
My favorit drinks

### PR DESCRIPTION
**Pull request by honeymoney98**
hello

### CODE REVIEW

**Comment by otherjuliagrace** [comment]
:dog:

**Comment by leilotuss** [comment]
I LOVE ORANGE JUICE

**Comment by leilotuss** [comment]
IT NEEDS TO LOVE ME BACK

**Comment by FishCakeIce** [comment]
I <3 milksoda

**Comment by FishCakeIce** [comment]
not milk or soda, milk and soda

**Pull request merged**
