### PR TITLE
Rename Chocolatesupport 1800md to Chocolatesupport 1800.md

### PR DESCRIPTION
**Pull request by Ilovechocolate18**
you can have fun everyday

### CODE REVIEW

**Comment by PatrickBM** [comment]
:tada:

**Comment by InternetPotato** [comment]
leg so hot
hot hot leg
leg so hot u fry an eg

**Comment by pkfire98** [comment]
How many middle aged men can fall off  segway scooters???

**Comment by QueenNymeria666** [comment]
many happy frogs danced with horses and koalas :frog: :dancer: :horse: :koala:

**Comment by QueenNymeria666** [comment]
as many feet that are consumed by fish

**Comment by pkfire98** [comment]
That's dark as my soul :neckbeard:

**Comment by QueenNymeria666** [comment]
:neckbeard: HELP!!!! THE SLOTHS ARE ATTACKING WE ARE ALL GOING TO DIE!!!!

**Pull request merged**
